// Start python tests/browser/serve_report_fixture.py, then run this script.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge'});
  const page = await browser.newPage({viewport: {width: 1920, height: 1080}});
  const base = process.env.REPORT_PREVIEW_URL || 'http://127.0.0.1:8771';
  const firstReport = base + '/artifacts/2026-10-03/reports/paper-0/report.html';
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  fs.mkdirSync('work/report-qa', {recursive: true});
  await page.goto(firstReport);
  await page.waitForSelector('.report-paper-link');
  assert.equal(await page.locator('.report-paper-link').count(), 3);
  assert.equal(await page.locator('.report-paper-link[aria-current="page"]').count(), 1);
  assert.equal(Math.round((await page.locator('#report-papers').boundingBox()).width), 320);
  const handle = await page.locator('#report-papers-resize').boundingBox();
  await page.mouse.move(handle.x + 6, handle.y + 100);
  await page.mouse.down();
  await page.mouse.move(handle.x - 54, handle.y + 100);
  await page.mouse.up();
  assert.equal(Math.round((await page.locator('#report-papers').boundingBox()).width), 380);
  await page.screenshot({path: 'work/report-qa/desktop.png'});
  await page.locator('#report-papers-search').fill('Ada');
  assert.equal(await page.locator('.report-paper-link').count(), 3);
  await page.locator('#report-papers-search').fill('2608.01977v1');
  assert.equal(await page.locator('.report-paper-link').count(), 1);
  await page.locator('#report-papers-search').fill('Visual Agents');
  assert.equal(await page.locator('.report-paper-link').count(), 1);
  await page.locator('.report-paper-link').click();
  await page.waitForURL('**/paper-1/report.html');
  await page.waitForSelector('.report-paper-link');
  assert.equal(await page.locator('#report-papers-search').inputValue(), 'Visual Agents');
  assert.equal(Math.round((await page.locator('#report-papers').boundingBox()).width), 380);
  assert.equal(await page.evaluate(() => scrollY), 0);
  await page.goBack();
  await page.waitForURL('**/paper-0/report.html');
  await page.waitForSelector('.report-paper-link');
  await page.locator('#report-papers-search').fill('no-such-paper');
  assert.equal(await page.locator('#report-papers-clear').isVisible(), true);
  await page.locator('#report-papers-clear').click();
  assert.equal(await page.locator('.report-paper-link').count(), 3);
  await page.locator('#report-papers-close').click();
  await page.reload();
  assert.equal(await page.locator('#report-papers').isVisible(), false);
  await page.locator('#report-papers-toggle').click();
  await page.waitForSelector('.report-paper-link');
  for (const width of [1440, 1100, 768, 390, 320]) {
    await page.setViewportSize({width, height: 900});
    if (width < 1440) {
      await page.waitForFunction(() => !document.querySelector('.report-shell').classList.contains('papers-open'));
      if (!await page.locator('#report-papers').isVisible()) await page.locator('#report-papers-toggle').click();
      assert.equal(await page.locator('#report-papers').getAttribute('role'), 'dialog');
      assert.equal(await page.locator('#report-papers-resize').isVisible(), false);
    }
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `overflow at ${width}`);
    await page.screenshot({path: `work/report-qa/width-${width}.png`});
  }
  await page.locator('#report-papers-search').fill('Visual Agents');
  await page.locator('.report-paper-link').click();
  await page.waitForURL('**/paper-1/report.html');
  await page.waitForSelector('.report-paper-link');
  assert.equal(await page.locator('#report-papers').isVisible(), true, 'drawer persists on navigation');
  await page.locator('#report-papers-close').click();
  await page.locator('.toc-toggle').click();
  assert.equal(await page.locator('#report-papers').isVisible(), false);
  assert.equal(await page.locator('.report-sidebar').evaluate(node => node.classList.contains('open')), true);
  await page.locator('#report-papers-toggle').click();
  assert.equal(await page.locator('.report-sidebar').evaluate(node => node.classList.contains('open')), false);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#report-papers').isVisible(), false);
  await page.locator('#report-papers-toggle').click();
  await page.locator('#report-papers-backdrop').click({position: {x: 3, y: 300}});
  assert.equal(await page.locator('#report-papers').isVisible(), false);
  await page.route('**/api/reports', route => route.fulfill({status: 503, body: '{}'}));
  await page.locator('#report-papers-toggle').click();
  await page.waitForSelector('#report-papers-retry:not([hidden])');
  await page.unroute('**/api/reports');
  await page.locator('#report-papers-retry').click();
  await page.waitForSelector('.report-paper-link');
  await page.emulateMedia({media: 'print'});
  assert.equal(await page.locator('#report-papers').isVisible(), false);
  assert.equal(await page.locator('#report-papers-backdrop').isVisible(), false);
  await page.emulateMedia({media: 'screen'});
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('Report catalog, resize, search, navigation, persistence, mobile drawers, retry and print passed.');
})().catch(error => { console.error(error); process.exit(1); });
